name: Continuous Integration
on: push

jobs:
  ci:
    name: CI
    uses: acidicoala/KoalaBox/.github/workflows/build-and-package.yml@da1db72f2ebf0a2b8b0138931e1f02b6c8a44500
    permissions:
      contents: write
    with:
      modules: >-
        ["UplayR2Unlocker"]

      zip_command: >
        zip -j $ZIP_NAME
        artifacts/*/*.dll

      config: Debug
