name: Continuous Integration
on: push

jobs:
  ci:
    name: CI
    uses: acidicoala/KoalaBox/.github/workflows/build-and-package.yml@3fd07c5427e822e71378256056b79ae470ac81d2
    permissions:
      contents: write
    with:
      modules: >-
        ["UplayR2Unlocker"]

      zip_command: >
        zip -j $ZIP_NAME
        artifacts/*/*.dll

      config: Debug
