name: Continuous Integration
on: push

jobs:
  ci:
    name: CI
    uses: acidicoala/KoalaBox/.github/workflows/build-and-package.yml@dd39f6c5a6c945ae1b8face240d7735833765460
    permissions:
      contents: write
    with:
      modules: >-
        ["UplayR2Unlocker"]

      zip_command: >
        zip -j $ZIP_NAME
        artifacts/*/*.dll
