name: Continuous Integration
on: push

jobs:
  ci:
    name: CI
    uses: acidicoala/KoalaBox/.github/workflows/build-and-package.yml@db2ee8fa2074b05f8d876f54e2a36486d0e69258
    permissions:
      contents: write
    with:
      modules: >-
        ["UplayR2Unlocker"]

      zip_command: >
        zip -j $ZIP_NAME
        artifacts/*/*.dll

      config: Debug
